console.log("false == 0",false == 0)
console.log("false === 0",false === 0)
console.log("false == ''",false == '')
console.log("false ===''",false ==='')
console.log("0 == ''",0 == '')
console.log("0 ===''",0 ==='')
console.log("undefined == null",undefined == null)
console.log("undefined === null",undefined === null)
console.log("null == false",null == false)
console.log("undefined == false",undefined == false)
console.log("null == 0",null == 0)
console.log("undefined == 0",undefined == 0)
console.log("Nan == null",NaN == null)
console.log("NaN == NaN",NaN == NaN)
